import { ReportTemplate } from './ReportTemplate.js'

export class DefaultTemplate extends ReportTemplate {
  render(): string {
    const html = `
<!DOCTYPE html>
<html lang="en" ${this.options.theme ? `data-theme="${this.options.theme}"` : ''}>
${this.renderHead()}
<body>
  <header class="report-header">
    <div class="header-content">
      <h1>${this.data.repository.name}</h1>
      <div class="header-meta">
        <span class="repo-path">${this.data.repository.path}</span>
        ${this.data.repository.url ? `
          <a href="${this.data.repository.url}" class="repo-link" target="_blank" rel="noopener">
            View on GitHub
          </a>
        ` : ''}
      </div>
    </div>
    <div class="header-actions">
      ${this.renderChart('theme-toggle')}
      <button class="export-button" aria-label="Export data">
        ${this.data.assets.icons.download}
      </button>
    </div>
  </header>

  <main class="report-content">
    <section class="metrics-section">
      <h2 class="section-title">Overview</h2>
      <div class="metrics-grid">
        ${this.renderMetricCards(['commits', 'contributors', 'files', 'lines'])}
      </div>
    </section>

    <section class="time-controls">
      ${this.renderChart('time-slider')}
      ${this.renderChart('chart-toggle')}
    </section>

    <section class="charts-section">
      <div class="chart-grid">
        <div class="chart-container full-width">
          <h3>Repository Growth</h3>
          ${this.renderChart('growth-chart')}
        </div>
        
        <div class="chart-container half-width">
          <h3>Code Distribution</h3>
          ${this.renderChart('file-types-pie')}
        </div>
        
        <div class="chart-container half-width">
          <h3>Top Contributors</h3>
          ${this.renderChart('contributor-bars')}
        </div>
        
        <div class="chart-container full-width">
          <h3>File Activity Heatmap</h3>
          ${this.renderChart('activity-heatmap')}
        </div>
      </div>
    </section>

    <section class="tables-section">
      <h2 class="section-title">File Analysis</h2>
      ${this.renderChart('top-files-table')}
    </section>

    <section class="insights-section">
      <h2 class="section-title">Insights</h2>
      <div class="insights-grid">
        ${this.renderChart('contributor-awards')}
        ${this.renderChart('commit-patterns')}
        ${this.renderChart('code-evolution')}
      </div>
    </section>
  </main>

  <footer class="report-footer">
    <p>Generated by <a href="https://github.com/user/repo-statter">repo-statter</a> on ${this.data.repository.analyzedAt.toLocaleString()}</p>
  </footer>

  ${this.renderScripts()}
</body>
</html>
    `
    
    return this.minifyHTML(html)
  }
  
  private renderScripts(): string {
    if (this.options.inlineAssets) {
      return `<script>${this.data.assets.scripts}</script>`
    }
    return '<script src="assets/scripts.js" defer></script>'
  }
}